---
  promotions:
    ring0:
      promote_from:
        - "ring0"
        - "prod-apps"
      promote_to:
        - "ring1"
        - "ring0"
        - "prod-apps"
      custom_items:
        GoogleChrome:
          days_in_catalog: 1
        Firefox:
          days_in_catalog: 2
    ring1:
      promote_to:
        - "ring2"
        - "ring1"
        - "ring0"
        - "prod-apps"
      promote_from:
        - "ring0"
        - "ring1"
        - "prod-apps"
      custom_items:
        GoogleChrome:
          days_in_catalog: 1
        Firefox:
          days_in_catalog: 2
  default_days_in_catalog: 3
  selection:
    type: exclusion
    items:
      - MicrosoftEdge
